package com.neasaa.base.app.operation;

public interface BeanNames {
	String AUTHORIZATION_SERVICE_BEAN = "AUTHORIZATION_SERVICE";
	String AUTHENTICATION_SERVICE_BEAN = "AUTHENTICATION_SERVICE_BEAN";
	String SESSION_SERVICE_BEAN = "SESSION_SERVICE_BEAN";
	
	String DATASOURCE_BEAN = "DATASOURCE";
	String JDBC_TEMPLATE_BEAN = "JDBC_TEMPLATE";
	
	String CACHE_MANAGER_BEAN = "CACHE_MANAGER";
	
	String TRANSACTION_MANAGER = "transactionManager";
}
