package com.neasaa.base.app.operation;

public interface OperationNames {
	String LOGIN = "LOGIN";
	String LOGOUT = "LOGOUT";
	
	String GET_SESSION_DETAILS = "GET_SESSION_DETAILS";
	String IS_SESSION_VALID = "IS_SESSION_VALID";
	
	String CHANGE_PASSWORD = "CHANGE_PASSWORD";
	String FORGOT_PASSWORD_REQUEST_OTP = "FORGOT_PASSWORD_REQUEST_OTP";
	String RESET_FORGOT_PASSWORD = "RESET_FORGOT_PASSWORD";
}
